# Generated by Django 6.0.3 on 2026-04-08 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('health', '🏥 Health & Medical'), ('education', '🎓 Education'), ('food', '🍱 Food & Nutrition'), ('infrastructure', '🏗️ Infrastructure'), ('sanitation', '🚿 Sanitation & Water'), ('elderly', '👵 Elderly & Disabled Care'), ('other', '📌 Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('urgency', models.CharField(choices=[('high', '🔴 High'), ('medium', '🟡 Medium'), ('low', '🟢 Low'), ('unscored', 'Not Scored Yet')], default='unscored', max_length=20)),
                ('ai_recommendation', models.TextField(blank=True, default='')),
                ('ai_scored', models.BooleanField(default=False)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='needs/')),
                ('source', models.CharField(choices=[('digital', 'Digital Submission'), ('digitized', 'Digitized Document'), ('public', 'Public Report')], default='digital', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to='core.ngo')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
