# Generated by Django 6.0.3 on 2026-04-08 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_needreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='documents/')),
                ('source_type', models.CharField(choices=[('photo', 'Paper Photo'), ('pdf', 'Scanned PDF'), ('sheet', 'Spreadsheet')], default='photo', max_length=20)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('extracted_title', models.CharField(blank=True, default='', max_length=200)),
                ('extracted_category', models.CharField(blank=True, default='', max_length=50)),
                ('extracted_location', models.CharField(blank=True, default='', max_length=200)),
                ('extracted_urgency', models.CharField(blank=True, default='', max_length=20)),
                ('is_converted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('linked_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='core.needreport')),
                ('ngo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.ngo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
