# Generated by Django 6.0.3 on 2026-04-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
