# Generated by Django 6.0.3 on 2026-04-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_volunteerprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngo',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
