# Generated by Django 6.0.3 on 2026-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ngo_latitude_ngo_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
