# Generated by Django 6.0.3 on 2026-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assignment_is_verified_assignment_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_verification', 'Awaiting Verification'), ('resolved', 'Resolved')], default='pending', max_length=30),
        ),
    ]
